Funtoo install begins

diff --git a/init.d/lvm b/init.d/lvm
--- a/init.d/lvm
+++ b/init.d/lvm
@@ -1,56 +1,48 @@
 #!/sbin/openrc-run
-# Copyright 1999-2020 Gentoo Authors
+# Copyright 1999-2017 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 _get_lvm_path() {
 	local lvm_path=
 	for lvm_path in /bin/lvm /sbin/lvm ; do
-		[ -x "${lvm_path}" ] && break
+		[ -x "$lvm_path" ] && break
 	done
 	echo "${lvm_path}"
 }
 
-_use_lvmetad() {
+_need_lvmetad()
+{
 	local lvm_path="$(_get_lvm_path)"
 	[ ! -x "${lvm_path}" ] && return 1
 	${lvm_path} dumpconfig global 2>/dev/null | grep -q 'use_lvmetad=1'
 }
 
-_use_lvmlockd() {
+_need_lvmlockd()
+{
 	local lvm_path="$(_get_lvm_path)"
 	[ ! -x "${lvm_path}" ] && return 1
 	${lvm_path} dumpconfig global 2>/dev/null | grep -q 'use_lvmlockd=1'
 }
-
 depend() {
 	before checkfs fsck
 	after modules device-mapper
-	# We may want lvmetad based on the configuration. If we added lvmetad
+	# We may use lvmetad based on the configuration. If we added lvmetad
 	# support while lvm2 is running then we aren't dependent on it. For the
 	# more common case, if its disabled in the config we aren't dependent
 	# on it.
 	config /etc/lvm/lvm.conf
-	local _want=
-
-	if service_started ; then
-		_want=$(service_get_value want)
+	local _need=
+	if service_started; then
+		_need=$(service_get_value need)
 	else
-		if _use_lvmetad ; then
-			_want="${_want} lvmetad"
+		if _need_lvmetad; then
+			_need="${_need} lvmetad"
 		fi
-
-		if _use_lvmlockd ; then
-			_want="${_want} lvmlockd"
+		if _need_lvmlockd; then
+			_need="${_need} lvmlockd"
 		fi
 	fi
-
-	# Make sure you review /etc/conf.d/lvm as well!
-	# Depending on your system, it might also introduce udev & mdraid
-	need sysfs
-
-	if [ -n "${_want}" ] ; then
-		want ${_want}
-	fi
+	need sysfs ${_need}
 }
 
 config='global { locking_dir = "/run/lock/lvm" }'
@@ -71,103 +63,83 @@ start() {
 
 	# NOTE: Add needed modules for LVM or RAID, etc
 	#       to /etc/modules.autoload if needed
-
 	lvm_path="$(_get_lvm_path)"
-	if [ -z "${lvm_path}" ] ; then
-		eerror "Failed to find lvm binary in /bin or /sbin!"
+	for lvm_path in /bin/lvm /sbin/lvm ; do
+		[ -x "$lvm_path" ] && break
+	done
+	if [ ! -x "$lvm_path" ]; then
+		eerror "Cannot find lvm binary in /sbin or /bin!"
 		return 1
 	fi
-
 	if [ -z "${CDBOOT}" ] ; then
 		if [ -e /proc/modules ] && ! dm_in_proc ; then
-			ebegin "Trying to load dm-mod module"
 			modprobe dm-mod 2>/dev/null
-			eend $?
 		fi
-
 		if [ -d /proc/lvm ] || dm_in_proc ; then
-			local has_errors=0 verbose_command
-
-			yesno "${rc_verbose}" && verbose_command=" -v"
-
-			ebegin "Starting the Logical Volume Manager"
-
-			if _use_lvmetad ; then
-				# Extra PV find pass because some devices might not have been available until very recently
-				${lvm_path} pvscan${verbose_command} --config "${config}" --cache
-				[ $? -ne 0 ] && has_errors=1
-			fi
-
+			ebegin "Setting up the Logical Volume Manager"
+			#still echo stderr for debugging
+			lvm_commands="#!${lvm_path}\n"
+			# Extra PV find pass because some devices might not have been available until very recently
+			lvm_commands="${lvm_commands}pvscan --config '${config}'\n"
 			# Now make the nodes
-			${lvm_path} vgscan${verbose_command} --config "${config}" --mknodes
-			[ $? -ne 0 ] && has_errors=1
-
-			# Enable all VGs
-			${lvm_path} vgchange${verbose_command} --config "${config}" --sysinit --activate y
-			[ $? -ne 0 ] && has_errors=1
-
-			if _use_lvmlockd ; then
+			lvm_commands="${lvm_commands}vgscan --config '${config}' --mknodes\n"
+			# And turn them on!
+			lvm_commands="${lvm_commands}vgchange --config '${config}' --sysinit -a ly\n"
+			if _need_lvmlockd; then
 				# Start lockd VGs as required
-				${lvm_path} vgchange${verbose_command} --config "${config}" --lock-start --lock-opt auto
-				[ $? -ne 0 ] && has_errors=1
+				lvm_commands="${lvm_commands}vgchange --config '${config}' --lock-start --lock-opt auto\n"
 			fi
-
-			eend ${has_errors} "Failed to start the Logical Volume Manager"
+			# Order of this is important, have to work around dash and LVM readline
+			printf "%b\n" "${lvm_commands}" | $lvm_path /proc/self/fd/0 >/dev/null
+			eend $? "Failed to setup the LVM"
 		fi
 	fi
 }
 
-start_post() {
-	local _want=
-	if _use_lvmetad ; then
-		_want="${_want} lvmetad"
+start_post()
+{
+	# Save if we needed lvmetad
+	if _need_lvmetad; then
+		service_set_value need lvmetad
 	fi
-
-	if _use_lvmlockd ; then
-		_want="${_want} lvmlockd"
-	fi
-
-	service_set_value want "${_want}"
 }
 
 stop() {
-	lvm_path="$(_get_lvm_path)"
-	if [ -z "${lvm_path}" ] ; then
-		eerror "Failed to find lvm binary in /bin or /sbin!"
+	for lvm_path in /bin/lvm /sbin/lvm ; do
+		[ -x "$lvm_path" ] && break
+	done
+	if [ ! -x "$lvm_path" ]; then
+		eerror "Cannot find lvm binary in /sbin or /bin!"
 		return 1
 	fi
+# Stop LVM2
+if [ -x /sbin/vgs ] && \
+   [ -x /sbin/vgchange ] && \
+   [ -x /sbin/lvchange ] && \
+   [ -f /etc/lvmtab -o -d /etc/lvm ] && \
+   [ -d /proc/lvm  -o "`grep device-mapper /proc/misc 2>/dev/null`" ]
+then
+	einfo "Shutting down the Logical Volume Manager"
 
-	# Stop LVM2
-	if [ -f /etc/lvmtab -o -d /etc/lvm ] \
-		&& [ -d /proc/lvm  -o "$(grep device-mapper /proc/misc 2>/dev/null)" ]
-	then
-		local VGS=$($lvm_path vgs --config "${config}" -o vg_name --noheadings --nosuffix --rows 2> /dev/null)
-		if [ -z "${VGS}" ] ; then
-			# nothing to do for us
-			return 0
-		fi
+        VGS=$($lvm_path vgs --config "${config}" -o vg_name --noheadings --nosuffix --rows 2> /dev/null)
 
-		local has_errors=0 verbose_command eend_cmd="eend"
+        if [ "$VGS" ]
+        then
+            ebegin "  Shutting Down LVs & VGs"
+			#still echo stderr for debugging
+			lvm_commands="#!${lvm_path}\n"
+			# Extra PV find pass because some devices might not have been available until very recently
+			lvm_commands="${lvm_commands}lvchange --config '${config}' --sysinit -a ln ${VGS}\n"
+			# Now make the nodes
+			lvm_commands="${lvm_commands}vgchange --config '${config}' --sysinit -a ln ${VGS}\n"
+			# Order of this is important, have to work around dash and LVM readline
+			printf "%b\n" "${lvm_commands}" | $lvm_path /proc/self/fd/0 --config "${config}" >/dev/null
+			eend $? "Failed (possibly some LVs still needed for /usr or root)"
+        fi
 
-		yesno "${rc_verbose}" && verbose_command=" -v"
-
-		local msg="Failed to stop Logical Volume Manager"
-		if [ "${RC_RUNLEVEL}" = shutdown ] ; then
-			# failures on shutdown are non-fatal
-			eend_cmd="ewend"
-			msg="${msg} (possibly some LVs still needed for /usr or root)"
-		fi
-
-		ebegin "Stopping the Logical Volume Manager"
-
-		${lvm_path} vgchange${verbose_command} --config "${config}" --sysinit --activate n
-		[ $? -ne 0 ] && has_errors=1
-
-		${eend_cmd} ${has_errors} "${msg}"
-	fi
-
-	# at this point make sure we always exit without indicating an error
+	einfo "Finished shutting down the Logical Volume Manager"
 	return 0
+fi
 }
 
 # vim:ts=4
diff --git a/init.d/net-online b/init.d/net-online
--- a/init.d/net-online
+++ b/init.d/net-online
@@ -13,64 +13,63 @@ description="Delays until the network is online or a specific timeout"
 
 depend()
 {
-	after modules net
+	before *
 	need sysfs
 	provide network-online
-	keyword -docker -jail -lxc -openvz -prefix -systemd-nspawn -uml -vserver
+	keyword -jail -prefix -systemd-nspawn
 }
 
 get_interfaces()
 {
 	local ifname iftype
 	for ifname in /sys/class/net/*; do
-		[ -h "${ifname}" ] && continue
 		read iftype < ${ifname}/type
 		[ "$iftype" = "1" ] && printf "%s " ${ifname##*/}
 	done
 }
 
+attempt_with_min_delay() {
+
+	# This function attempts something repeatedly, but if it takes less than one second then
+	# it detects this and inserts an artificial 0.5 second "setup delay" so it doesn't blow
+	# through all attempts too quickly. Good for when the connectivity test is failing
+	# immediately due to DNS resolution error, etc, so makes the connectivity test much easier
+	# to write. This connectivity test actually turns out to be a tricky little problem!
+	# This should solve it.
+
+	local count=0
+	local max_attempts=$1
+	local cmd="$2"
+	ebegin "Performing connectivity test (attempts=$max_attempts)"
+	while [ $count -lt $max_attempts ]; do
+		count=$[ $count + 1 ]
+		local ts_start=$(date +%s%N)
+		eval $cmd
+		if [ $? -eq 0 ]; then
+			return 0
+		fi
+		local ts_stop=$(date +%s%N)
+		local ts_diff=$[ $ts_stop - $ts_start ]
+		if [ $count -lt $max_attempts ] && [ $ts_diff -lt 1000000000 ]; then
+			# command took less than 1 sec to run; so wait at least 0.5 seconds between attempts
+			sleep 0.5
+		fi
+	done
+	return 1
+}
+
 start ()
 {
-	local carriers configured dev gateway ifcount infinite
-	local carrier operstate rc
-
-	ebegin "Checking to see if the network is online"
-	rc=0
-	interfaces=${interfaces:-$(get_interfaces)}
-	timeout=${timeout:-120}
- [ $timeout -eq 0 ] && infinite=true || infinite=false
- while $infinite || [ $timeout -gt 0 ]; do
-	carriers=0
-	configured=0
-	ifcount=0
- 	for dev in ${interfaces}; do
-		: $((ifcount += 1))
-		read carrier < /sys/class/net/$dev/carrier 2> /dev/null ||
-			carrier=
-		[ "$carrier" = 1 ] && : $((carriers += 1))
-		read operstate < /sys/class/net/$dev/operstate 2> /dev/null ||
-			operstate=
-		[ "$operstate" = up ] && : $((configured += 1))
-	done
-	[ $configured -eq $ifcount ] && [ $carriers -ge 1 ] && break
-	sleep 1
-	: $((timeout -= 1))
- done
- ! $infinite && [ $timeout -eq 0 ] && rc=1
- include_ping_test=${include_ping_test:-${ping_default_gateway}}
- if [ -n "${ping_default_gateway}" ]; then
- ewarn "ping_default_gateway is deprecated, please use include_ping_test"
- fi
- if [ $rc -eq 0 ] && yesno ${include_ping_test:-no}; then
- 	ping_test_host="${ping_test_host:-google.com}"
- 	if [ -n "$ping_test_host" ]; then
-		while $infinite || [ $timeout -gt 0 ]; do
-			ping -c 1 $ping_test_host > /dev/null 2>&1
-			rc=$?
-			[ $rc -eq 0 ] && break
-			: $((timeout -= 1))
-		done
+	if [ -n "$connectivity_test" ]; then
+		attempt_with_min_delay "${connectivity_attempts:-10}" "$connectivity_test"
+		success=$?
+		if [ $success -eq 0 ]; then
+			eend 0 "The network is now connected"
+		else
+			# There is not a huge benefit in failing here. Doing so could prevent normal, timely startup.
+			# Better to just continue.
+			eend 1 "The network failed to connect. Continuing anyway."
+		fi
 	fi
- fi
- eend $rc "The network is offline"
+	return 0
 }
